version: '3.7'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - ./app:/var/www/html/app
      - ./logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - socket:/sock
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/sock
    ports:
      - "9000:9000"
    networks:
      - app-network

  maria_db:
    image: mariadb
    container_name: maria_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "33062:3306"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.7.5-management
    volumes:
      - ./app:/var/www/html/app
    hostname: rabbit-mq
    container_name: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network

volumes:
  socket:
    driver: local

networks:
  app-network:
    driver: bridge